# -*- coding: utf-8 -*-
"""ConvertPixelstomm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjqv1s3IKrBOLHdvecfSOWls1WUYXohj
"""

deltax = 0.007972665 #mm/pixel
deltay = 0.007575757 #mm/pixel

#returns list of x, y arrays
def convertpixtomm(xarray, deltax, yarray, deltay):
    xarraymm = xarray*deltax
    yarraymm = yarray*deltay
    return [xarraymm, yarraymm]

'''
xarray = np.array([0,1,2,3,4,5,6,7,8,9])
yarray = np.array([0,1,2,3,4,5,6,7,8,9])

print(convertpixtomm(xarray, deltax, yarray, deltay))
'''

